package com.example.lmiptv

import android.net.Uri
import android.os.Bundle
import android.util.Base64
import android.graphics.Bitmap
import android.view.KeyEvent
import android.view.View
import android.view.ViewGroup
import android.view.WindowManager
import android.widget.FrameLayout
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.focusable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.Image
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.rememberLazyGridState
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.lazy.grid.itemsIndexed
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.tween
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.Crossfade
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.onFocusChanged
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.input.key.onPreviewKeyEvent
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.KeyEventType
import androidx.compose.ui.input.key.key
import androidx.compose.ui.input.key.type
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil3.compose.AsyncImage
import androidx.compose.ui.viewinterop.AndroidView
import androidx.lifecycle.lifecycleScope
import androidx.media3.common.MediaItem
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.ui.PlayerView
import androidx.media3.ui.DefaultTimeBar
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.coroutines.delay
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import org.json.JSONArray
import org.json.JSONObject
import com.google.zxing.BarcodeFormat
import com.google.zxing.qrcode.QRCodeWriter
import fi.iki.elonen.NanoHTTPD
import java.io.BufferedReader
import java.io.InputStreamReader
import java.net.HttpURLConnection
import java.net.URL
import java.net.NetworkInterface
import java.net.URLEncoder
import java.util.Collections
import java.util.zip.GZIPInputStream
import org.xmlpull.v1.XmlPullParser
import org.xmlpull.v1.XmlPullParserFactory

data class IptvItem(val id:String,val title:String,val url:String,val group:String,val kind:String,val seriesId:String?=null,val image:String="",val streamId:String="",val epgId:String="")
data class Category(val id:String,val name:String)
data class Xtream(val server:String,val username:String,val password:String,val playlistUrl:String="")
data class Imported(val xtream:Xtream?,val categories:Map<String,List<Category>>,val items:List<IptvItem>)
data class PlaylistProfile(val name:String,val url:String,val avatar:Int=0)
data class MediaDetails(val title:String,val plot:String="",val year:String="",val genre:String="",val rating:String="",val duration:String="",val director:String="",val cast:String="")

class MainActivity:ComponentActivity(){
  private var player:ExoPlayer?=null
  private var live=false
  private var changeChannel:((Int)->Unit)?=null
  private var revealPlayerInfo:(()->Unit)?=null
  private var playerControlsVisible=false
  private var controlsPulse=0
  private var lastHeldSeek=0L
  override fun onCreate(state:Bundle?){super.onCreate(state);window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);setContent{LmFireTv{media,isLive,onStep,onReveal->player=media;live=isLive;changeChannel=onStep;revealPlayerInfo=onReveal;if(media==null)playerControlsVisible=false}}}
  fun setPlayerControlsVisible(visible:Boolean){playerControlsVisible=visible}
  private fun armPlayerControls(){playerControlsVisible=true;val pulse=++controlsPulse;window.decorView.postDelayed({if(pulse==controlsPulse)playerControlsVisible=false},3200)}
  override fun dispatchKeyEvent(event:KeyEvent):Boolean{if(event.action==KeyEvent.ACTION_DOWN&&player!=null){if(playerControlsVisible)armPlayerControls();when(event.keyCode){
    KeyEvent.KEYCODE_DPAD_CENTER,KeyEvent.KEYCODE_ENTER->{armPlayerControls();revealPlayerInfo?.invoke();return super.dispatchKeyEvent(event)}
    KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE,KeyEvent.KEYCODE_SPACE->{if(player!!.isPlaying)player!!.pause()else player!!.play();return true}
    KeyEvent.KEYCODE_MEDIA_PLAY->{player!!.play();return true};KeyEvent.KEYCODE_MEDIA_PAUSE->{player!!.pause();return true}
    KeyEvent.KEYCODE_DPAD_RIGHT->{if(live){if(event.repeatCount==0)changeChannel?.invoke(1);return true};return if(playerControlsVisible)super.dispatchKeyEvent(event)else true}
    KeyEvent.KEYCODE_DPAD_LEFT->{if(live){if(event.repeatCount==0)changeChannel?.invoke(-1);return true};return if(playerControlsVisible)super.dispatchKeyEvent(event)else true}
    KeyEvent.KEYCODE_DPAD_UP,KeyEvent.KEYCODE_DPAD_DOWN->{return if(playerControlsVisible)super.dispatchKeyEvent(event)else true}
    KeyEvent.KEYCODE_MEDIA_FAST_FORWARD->{player!!.seekTo(player!!.currentPosition+30_000);return true};KeyEvent.KEYCODE_MEDIA_REWIND->{player!!.seekTo((player!!.currentPosition-10_000).coerceAtLeast(0));return true}
  }};return super.dispatchKeyEvent(event)}
  override fun onResume(){super.onResume();window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)}
  override fun onStop(){super.onStop();player?.pause()};override fun onDestroy(){window.clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);player?.release();player=null;super.onDestroy()}
}

@Composable fun LmFireTv(onPlayer:(ExoPlayer?,Boolean,((Int)->Unit)?,(()->Unit)?)->Unit){
  val context=LocalContext.current;val prefs=remember{context.getSharedPreferences("lm_iptv_firetv",0)};val scope=(context as ComponentActivity).lifecycleScope
  var splash by remember{mutableStateOf(true)};var exitDialog by remember{mutableStateOf(false)};var setupSelection by remember{mutableStateOf(false)};var pendingProfile by remember{mutableStateOf<PlaylistProfile?>(null)};var resumeRevision by remember{mutableIntStateOf(0)};var mediaDetails by remember{mutableStateOf<MediaDetails?>(null)};var infoLoading by remember{mutableStateOf(false)}
  var url by remember{mutableStateOf(prefs.getString("playlist_url","")?:"")};var name by remember{mutableStateOf(prefs.getString("source_name","La mia playlist")?:"La mia playlist")};var profiles by remember{mutableStateOf(readProfiles(prefs.getString("profiles","[]")?:"[]").ifEmpty{if(url.isBlank())emptyList()else listOf(PlaylistProfile(name,url))})};var profileSelection by remember{mutableStateOf(false)}
  var xtream by remember{mutableStateOf<Xtream?>(null)};var categoryMap by remember{mutableStateOf<Map<String,List<Category>>>(emptyMap())};var catalog by remember{mutableStateOf<List<IptvItem>>(emptyList())};var homeMovies by remember{mutableStateOf<List<IptvItem>>(emptyList())};var homeLive by remember{mutableStateOf<List<IptvItem>>(emptyList())}
  var section by remember{mutableStateOf("HOME")};var category by remember{mutableStateOf<Category?>(null)};var query by remember{mutableStateOf("")};var loading by remember{mutableStateOf(false)};var status by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};var settings by remember{mutableStateOf(url.isBlank())};var current by remember{mutableStateOf<IptvItem?>(null)}
  var seriesTitle by remember{mutableStateOf<String?>(null)};var previousSeriesList by remember{mutableStateOf<List<IptvItem>>(emptyList())};var epgNow by remember{mutableStateOf<Map<String,String>>(emptyMap())};var favorites by remember{mutableStateOf(readFavorites(prefs.getString("favorites","[]")?:"[]"))};var searchCatalog by remember{mutableStateOf<List<IptvItem>>(emptyList())};var searchLoading by remember{mutableStateOf(false)};var hiddenGroups by remember{mutableStateOf(prefs.getStringSet("hidden_groups",emptySet())?.toSet()?:emptySet())};var groupOrder by remember{mutableStateOf(readStringList(prefs.getString("group_order","[]")?:"[]"))};var expiry by remember{mutableStateOf("Non disponibile")};var initializing by remember{mutableStateOf(false)};var preloadDone by remember{mutableIntStateOf(0)};var preloadTotal by remember{mutableIntStateOf(1)};var preloadLabel by remember{mutableStateOf("Preparazione…")}
  val mediaGridState=rememberLazyGridState();val returnFocusRequester=remember{FocusRequester()};var lastFocusedId by remember{mutableStateOf<String?>(null)};var restoreFocusPending by remember{mutableStateOf(false)};var seriesParentFocusId by remember{mutableStateOf<String?>(null)};var seriesParentGroup by remember{mutableStateOf<String?>(null)};var seriesGridIndex by remember{mutableIntStateOf(0)};var seriesGridOffset by remember{mutableIntStateOf(0)}

  fun loadRemote(target:String,cat:Category){val config=xtream?:return;val apiTarget=if(target=="GUIDA TV")"LIVE"else target;section=target;category=cat;query="";seriesTitle=null;loading=true;status="Caricamento ${cat.name}…";error="";scope.launch{try{val loaded=withContext(Dispatchers.IO){loadXtreamCategory(config,apiTarget,cat)};catalog=loaded}catch(e:Exception){error=e.message?:"Categoria non disponibile";catalog=emptyList()}finally{loading=false;status=""}}}
  fun selectCategory(target:String,cat:Category){val kind=if(target=="GUIDA TV")"LIVE"else target;val ready=searchCatalog.filter{it.kind==kind&&it.group==cat.name};if(ready.isNotEmpty()){section=target;category=cat;catalog=ready;query="";seriesTitle=null}else loadRemote(target,cat)}
  fun switchSection(target:String){section=target;seriesTitle=null;if(target=="HOME"){category=null;query="";return};if(target=="CERCA"){category=null;query="";if(searchCatalog.isEmpty()&&xtream!=null&&!searchLoading){searchLoading=true;scope.launch{try{searchCatalog=withContext(Dispatchers.IO){loadFullCatalog(xtream!!,categoryMap)}}catch(e:Exception){error=e.message?:"Ricerca non disponibile"}finally{searchLoading=false}}};return};if(target=="PREFERITI"){catalog=favorites;category=null;query="";return};val mapKey=if(target=="GUIDA TV")"LIVE"else target;val first=categoryMap[mapKey]?.firstOrNull{!hiddenGroups.contains("$mapKey:${it.id}")};if(xtream!=null&&first!=null)selectCategory(target,first)else{category=null;query=""}}
  fun toggleFavorite(item:IptvItem){favorites=if(favorites.any{it.id==item.id})favorites.filterNot{it.id==item.id}else favorites+item;prefs.edit().putString("favorites",writeFavorites(favorites)).apply();if(section=="PREFERITI")catalog=favorites}
  fun moveGroup(key:String,step:Int){val kind=key.substringBefore(":");val sectionKeys=categoryMap[kind].orEmpty().map{"$kind:${it.id}"};val sectionOrder=(groupOrder.filter{it in sectionKeys}+sectionKeys).distinct().toMutableList();val index=sectionOrder.indexOf(key);val target=(index+step).coerceIn(0,sectionOrder.lastIndex);if(index>=0&&index!=target){val value=sectionOrder.removeAt(index);sectionOrder.add(target,value);val other=groupOrder.filterNot{it in sectionKeys};val allKnown=categoryMap.flatMap{(section,cats)->cats.map{"$section:${it.id}"}};groupOrder=(other+sectionOrder+allKnown).distinct();prefs.edit().putString("group_order",writeStringList(groupOrder)).apply()}}
  fun connect(address:String=url,sourceName:String=name){if(address.isBlank()){error="Inserisci il link della playlist";return};url=address;name=sourceName;loading=true;status="Aggiornamento playlist…";error="";scope.launch{try{val data=withContext(Dispatchers.IO){importSource(address)};val isNewProfile=profiles.none{it.url==address};val setupCategories=if(data.categories.isNotEmpty())data.categories else data.items.groupBy{it.kind}.mapValues{entry->entry.value.map{it.group}.distinct().map{Category(it,it)}};if(isNewProfile&&setupCategories.isNotEmpty()){xtream=data.xtream;categoryMap=setupCategories;catalog=data.items;val created=PlaylistProfile(sourceName,address);profiles=profiles+created;prefs.edit().putString("playlist_url",address).putString("source_name",sourceName).putString("profiles",writeProfiles(profiles)).apply();hiddenGroups=setupCategories.flatMap{(kind,cats)->cats.map{"$kind:${it.id}"}}.toSet();prefs.edit().putStringSet("hidden_groups",hiddenGroups).apply();pendingProfile=created;setupSelection=true;profileSelection=false;settings=false;return@launch};xtream=data.xtream;categoryMap=data.categories;catalog=data.items;val updated=(profiles.filterNot{it.url==address}+PlaylistProfile(sourceName,address));profiles=updated;prefs.edit().putString("playlist_url",address).putString("source_name",sourceName).putString("profiles",writeProfiles(updated)).apply();settings=false;profileSelection=false;if(data.xtream!=null){expiry=withContext(Dispatchers.IO){subscriptionExpiry(data.xtream)};val first=data.categories["LIVE"]?.firstOrNull();if(first!=null){category=first;status="Preparazione Home…";val prepared=withContext(Dispatchers.IO){prepareHome(data.xtream,data.categories)};homeLive=prepared.first;homeMovies=prepared.second;catalog=homeLive.ifEmpty{loadXtreamCategory(data.xtream,"LIVE",first)};section="HOME"}}else{expiry="Non fornita per collegamenti M3U";homeLive=data.items.filter{it.kind=="LIVE"};homeMovies=data.items.filter{it.kind=="FILM"&&!isAdult(it.group)};section="HOME"}}catch(e:Exception){error=e.message?:"Importazione non riuscita"}finally{loading=false;status=""}}}
  fun preloadProfile(profile:PlaylistProfile,force:Boolean=false){
    url=profile.url;name=profile.name;profileSelection=false;setupSelection=false;initializing=true;preloadDone=0;preloadTotal=1;preloadLabel="Preparazione del profilo…";error=""
    scope.launch{try{
      val cached=if(force)null else withContext(Dispatchers.IO){readCatalogCache(context,profile.url)}
      if(cached!=null){
        preloadLabel="Apertura catalogo e Guida TV salvati…";categoryMap=cached.categories;searchCatalog=cached.items;epgNow=withContext(Dispatchers.IO){readEpgCache(context,profile.url)}?:cached.epg;xtream=parseXtream(profile.url);val selectedGroups=categoryMap["LIVE"].orEmpty().filterNot{hiddenGroups.contains("LIVE:${it.id}")}.map{it.name}.toSet();val selectedLive=searchCatalog.filter{it.kind=="LIVE"&&it.group in selectedGroups};preloadTotal=(selectedGroups.size+1).coerceAtLeast(1);preloadDone=1;val config=xtream;if(config!=null&&selectedLive.isNotEmpty()){val fresh=withContext(Dispatchers.IO){loadBestCurrentPrograms(config,selectedLive){group,done,_->scope.launch{preloadLabel="Caricamento EPG • $group";preloadDone=(done+1).coerceAtMost(preloadTotal)}}};if(fresh.isNotEmpty()){epgNow=epgNow+fresh;withContext(Dispatchers.IO){saveEpgCache(context,profile.url,epgNow)}}};preloadDone=preloadTotal
      }else{
        preloadLabel="Connessione alla playlist…";val data=withContext(Dispatchers.IO){importSource(profile.url)};xtream=data.xtream
        val effectiveCategories=if(data.categories.isNotEmpty())data.categories else categoryMap;categoryMap=effectiveCategories;prefs.edit().putString("playlist_url",profile.url).putString("source_name",profile.name).apply();val config=data.xtream
        if(config==null){preloadTotal=2;preloadLabel="Indicizzazione titoli…";val hiddenNames=effectiveCategories.flatMap{(kind,cats)->cats.filter{hiddenGroups.contains("$kind:${it.id}")}.map{it.name}}.toSet();searchCatalog=data.items.filterNot{hiddenNames.contains(it.group)};epgNow=emptyMap();preloadDone=2}else{
          val jobs=listOf("LIVE","FILM","SERIE").flatMap{kind->effectiveCategories[kind].orEmpty().filterNot{hiddenGroups.contains("$kind:${it.id}")}.sortedBy{val p=groupOrder.indexOf("$kind:${it.id}");if(p<0)Int.MAX_VALUE else p}.map{kind to it}}
          preloadTotal=(jobs.size+2).coerceAtLeast(1);val all=mutableListOf<IptvItem>()
          for((kind,cat)in jobs){preloadLabel="Caricamento ${cat.name}";all+=withContext(Dispatchers.IO){runCatching{loadXtreamCategory(config,kind,cat)}.getOrDefault(emptyList())};preloadDone++}
          val liveItems=all.filter{it.kind=="LIVE"};val epgGroups=liveItems.map{it.group}.distinct();val epgStart=preloadDone;preloadTotal=epgStart+epgGroups.size+1;preloadLabel="Preparazione Guida TV…";epgNow=withContext(Dispatchers.IO){loadBestCurrentPrograms(config,liveItems){group,done,_->scope.launch{preloadLabel="Caricamento EPG • $group";preloadDone=(epgStart+done).coerceAtMost(preloadTotal)}}};preloadDone=epgStart+epgGroups.size
          preloadLabel="Indicizzazione di ${all.size} titoli…";searchCatalog=all.distinctBy{it.id};preloadDone++;expiry=withContext(Dispatchers.IO){subscriptionExpiry(config)}
        }
        preloadLabel="Salvataggio nella memoria dell’app…";withContext(Dispatchers.IO){saveCatalogCache(context,profile.url,searchCatalog,epgNow,effectiveCategories);saveEpgCache(context,profile.url,epgNow)}
      }
      homeLive=searchCatalog.filter{it.kind=="LIVE"};homeMovies=searchCatalog.filter{it.kind=="FILM"&&!isAdult(it.group)&&!isAdult(it.title)}.shuffled();val first=categoryMap["LIVE"].orEmpty().firstOrNull{!hiddenGroups.contains("LIVE:${it.id}")};category=first;catalog=if(first==null)emptyList()else searchCatalog.filter{it.kind=="LIVE"&&it.group==first.name};section="HOME";settings=false
    }catch(e:Exception){error=e.message?:"Aggiornamento non riuscito";settings=true}finally{initializing=false;loading=false;preloadLabel=""}}
  }
  fun saveProfileEdit(old:PlaylistProfile,updated:PlaylistProfile){if(old.url!=updated.url)deleteCatalogCache(context,old.url);profiles=profiles.map{if(it.url==old.url)updated else it};prefs.edit().putString("profiles",writeProfiles(profiles)).apply();if(url==old.url){url=updated.url;name=updated.name;prefs.edit().putString("playlist_url",url).putString("source_name",name).apply()}}
  fun deleteProfile(profile:PlaylistProfile){deleteCatalogCache(context,profile.url);profiles=profiles.filterNot{it.url==profile.url};prefs.edit().putString("profiles",writeProfiles(profiles)).apply();if(url==profile.url){url="";name="La mia playlist";searchCatalog=emptyList();catalog=emptyList();epgNow=emptyMap();settings=false;profileSelection=true}}
  fun clearContinueWatching(){val editor=prefs.edit();prefs.all.keys.filter{it.startsWith("resume_")}.forEach{editor.remove(it)};editor.apply();resumeRevision++}
  fun showInfo(item:IptvItem){if(item.kind=="LIVE")return;infoLoading=true;scope.launch{mediaDetails=withContext(Dispatchers.IO){xtream?.let{runCatching{loadMediaDetails(it,item)}.getOrNull()}?:MediaDetails(item.title,plot="Informazioni non fornite dal server")};infoLoading=false}}
  fun open(item:IptvItem){lastFocusedId=item.id;if(item.kind=="SERIE"&&item.seriesId!=null&&xtream!=null){seriesParentFocusId=item.id;seriesParentGroup=item.group;seriesGridIndex=mediaGridState.firstVisibleItemIndex;seriesGridOffset=mediaGridState.firstVisibleItemScrollOffset;loading=true;status="Caricamento episodi…";error="";scope.launch{try{previousSeriesList=catalog;catalog=withContext(Dispatchers.IO){loadEpisodes(xtream!!,item)};seriesTitle=item.title;category=null;mediaGridState.scrollToItem(0)}catch(e:Exception){error=e.message?:"Episodi non disponibili"}finally{loading=false;status=""}}}else current=item}

  LaunchedEffect(Unit){delay(2200);splash=false;when{profiles.size==1->preloadProfile(profiles.first());profiles.size>1->profileSelection=true}}
  if(splash){SplashScreen();return}
  if(profileSelection){BackHandler{profileSelection=false;settings=true};ProfileSelector(profiles,{profile->preloadProfile(profile)},{profile->val updated=profiles.map{if(it.url==profile.url)it.copy(avatar=(it.avatar+1)%12)else it};profiles=updated;prefs.edit().putString("profiles",writeProfiles(updated)).apply()},{profileSelection=false;settings=true});return}
  if(setupSelection){CategorySetupScreen(categoryMap,hiddenGroups,{key->hiddenGroups=if(hiddenGroups.contains(key))hiddenGroups-key else hiddenGroups+key;prefs.edit().putStringSet("hidden_groups",hiddenGroups).apply()},{pendingProfile?.let{preloadProfile(it)}});return}
  if(loading&&status=="Aggiornamento playlist…"){PreloadScreen(name,"Analisi playlist e categorie…",0,0);return}
  if(initializing){PreloadScreen(name,preloadLabel,preloadDone,preloadTotal);return}
  if(current!=null){
    val playing=current!!;val queue=catalog.filter{it.kind=="LIVE"&&(category==null||it.group==category!!.name)}
    MaterialTheme(colorScheme=darkColorScheme(onSurface=Color.White)){Surface(color=Color.Black,contentColor=Color.White){key(playing.id){
    TvPlayer(playing,epgNow[playing.id],queue.indexOfFirst{it.id==playing.id}.takeIf{it>=0}?.plus(1),{current=null;restoreFocusPending=true;onPlayer(null,false,null,null)}){media,reveal->
        val stepper:((Int)->Unit)?=if(media==null)null else {step->if(queue.isNotEmpty()){val index=queue.indexOfFirst{it.id==playing.id}.coerceAtLeast(0);current=queue[(index+step+queue.size)%queue.size]}}
        onPlayer(media,playing.kind=="LIVE",stepper,reveal)
      }
    }}}
    return
  }
  BackHandler(enabled=seriesTitle!=null){catalog=previousSeriesList;seriesTitle=null;category=categoryMap["SERIE"]?.firstOrNull{it.name==seriesParentGroup};lastFocusedId=seriesParentFocusId;restoreFocusPending=true}
  BackHandler(enabled=seriesTitle==null){if(settings)settings=false else exitDialog=true}
  LaunchedEffect(restoreFocusPending,current,seriesTitle){if(restoreFocusPending&&current==null){delay(180);if(lastFocusedId==seriesParentFocusId)mediaGridState.scrollToItem(seriesGridIndex,seriesGridOffset);runCatching{returnFocusRequester.requestFocus()};restoreFocusPending=false}}
  val hiddenNames=categoryMap.flatMap{(kind,cats)->cats.filter{hiddenGroups.contains("$kind:${it.id}")}.map{it.name}}.toSet();val localGroups=if(section in listOf("HOME","CERCA","PREFERITI"))emptyList()else if(xtream==null||seriesTitle!=null)catalog.map{it.group}.distinct().filterNot{hiddenNames.contains(it)}.map{Category(it,it)}else{val key=if(section=="GUIDA TV")"LIVE"else section;categoryMap[key].orEmpty().filterNot{hiddenGroups.contains("$key:${it.id}")}.sortedBy{val index=groupOrder.indexOf("$key:${it.id}");if(index<0)Int.MAX_VALUE else index}};val visible=catalog.filter{!hiddenNames.contains(it.group)&&(category==null||it.group==category!!.name)&&(query.isBlank()||it.title.contains(query,true))}
  val stepContentGroup:(Int)->Unit={step->if(seriesTitle==null&&section in listOf("LIVE","FILM","SERIE")&&localGroups.isNotEmpty()){val currentIndex=localGroups.indexOfFirst{it.id==category?.id}.coerceAtLeast(0);val next=localGroups[(currentIndex+step+localGroups.size)%localGroups.size];val nextItems=searchCatalog.filter{it.kind==section&&it.group==next.name};if(nextItems.isNotEmpty()){category=next;catalog=nextItems;query="";lastFocusedId=nextItems.first().id;restoreFocusPending=true;scope.launch{mediaGridState.scrollToItem(0)}}else selectCategory(section,next)}}
  MaterialTheme(colorScheme=darkColorScheme(background=Color(0xFF050812),surface=Color(0xFF0D1422),primary=Color(0xFF3EE7E1),onBackground=Color.White,onSurface=Color.White,onPrimary=Color(0xFF06101A))){Surface(Modifier.fillMaxSize(),color=Color.Transparent,contentColor=Color.White){Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0xFF071426),Color(0xFF050812))))){Column(Modifier.fillMaxSize()){
    Row(Modifier.fillMaxWidth().height(62.dp).background(Color(0xF5060A14)).padding(horizontal=24.dp),verticalAlignment=Alignment.CenterVertically){Image(painterResource(R.drawable.lm_logo),"LM",Modifier.size(38.dp));Spacer(Modifier.width(18.dp));SearchNav(section=="CERCA"&&!settings){switchSection("CERCA");settings=false};listOf("HOME","FILM","SERIE","LIVE","GUIDA TV","PREFERITI").forEach{label->TopNav(label,section==label&&!settings){switchSection(label);settings=false}};Spacer(Modifier.weight(1f));DigitalClock();Spacer(Modifier.width(12.dp));TopNav("PROFILI",false){profileSelection=true};TopNav("IMPOSTAZIONI",settings){settings=true}}
    Column(Modifier.weight(1f).padding(horizontal=28.dp,vertical=16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(if(settings)"Playlist e impostazioni"else seriesTitle?:when(section){"HOME"->"";"CERCA"->"Cerca in LM IPTV";"LIVE"->"TV in diretta";"GUIDA TV"->"Guida TV";"FILM"->"Film";"SERIE"->"Serie TV";else->"I miei preferiti"},fontSize=22.sp,fontWeight=FontWeight.SemiBold,color=Color.White);if(section!="HOME")Text(name,color=Color(0xFFB8C2D3),fontSize=11.sp)};if(section=="CERCA")OutlinedTextField(query,{query=it},placeholder={Text("Canali, film e serie…")},singleLine=true,colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Color.White,unfocusedTextColor=Color.White,focusedBorderColor=Color(0xFF3EE7E1)),modifier=Modifier.width(420.dp).height(52.dp))};Spacer(Modifier.height(if(section=="HOME")2.dp else 12.dp))
      if(settings)Settings(name,{name=it},url,{url=it},loading,error,{if(profiles.any{it.url==url})preloadProfile(PlaylistProfile(name,url),true)else connect()},categoryMap,hiddenGroups,{key->hiddenGroups=if(hiddenGroups.contains(key))hiddenGroups-key else hiddenGroups+key;prefs.edit().putStringSet("hidden_groups",hiddenGroups).apply()},{key,step->moveGroup(key,step)},groupOrder,profiles,{old,updated->saveProfileEdit(old,updated)},{profile->deleteProfile(profile)}){phoneName,phoneUrl->connect(phoneUrl,phoneName)}else if(section=="HOME")HomeDashboard(homeMovies.filterNot{hiddenNames.contains(it.group)},homeLive.filterNot{hiddenNames.contains(it.group)},favorites.filterNot{hiddenNames.contains(it.group)},resumeRevision.let{searchCatalog.filter{item->item.kind!="LIVE"&&prefs.getLong("resume_${item.id}",0)>0&&!hiddenNames.contains(item.group)}},epgNow,{open(it)},{clearContinueWatching()})else if(section=="CERCA")SearchScreen(searchCatalog.filterNot{hiddenNames.contains(it.group)},query,searchLoading,epgNow,{open(it)},{showInfo(it)})else{if(localGroups.isNotEmpty())LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(localGroups){cat->TvChip(cat.name,category?.name==cat.name){if(xtream!=null&&seriesTitle==null&&section!="PREFERITI")selectCategory(section,cat)else category=cat}}};Spacer(Modifier.height(10.dp));Row{Text(if(loading)status else "${visible.size} contenuti",color=Color(0xFFB8C2D3),fontSize=11.sp);if(error.isNotBlank()){Spacer(Modifier.width(18.dp));Text(error,color=Color(0xFFFF8295),fontSize=11.sp)}};Spacer(Modifier.height(9.dp));if(loading)Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){CircularProgressIndicator();Spacer(Modifier.height(12.dp));Text(status,fontSize=12.sp,color=Color.White)}}else if(visible.isEmpty())Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text(if(section=="PREFERITI")"Non hai ancora aggiunto preferiti"else if(error.isNotBlank())error else "Nessun contenuto disponibile",color=Color.White) }else if(section=="GUIDA TV")GuideTvScreen(visible,epgNow,{open(it)})else LazyVerticalGrid(columns=GridCells.Fixed(4),state=mediaGridState,horizontalArrangement=Arrangement.spacedBy(14.dp),verticalArrangement=Arrangement.spacedBy(15.dp),contentPadding=PaddingValues(4.dp,4.dp,4.dp,40.dp)){itemsIndexed(visible,key={_,item->item.id}){index,item->val groupEdge:((Int)->Boolean)={step->val atEdge=(step<0&&index%4==0)||(step>0&&(index%4==3||index==visible.lastIndex));if(atEdge)stepContentGroup(step);atEdge};MediaCard(item,epgNow[item.id],favorites.any{f->f.id==item.id},{toggleFavorite(item)},{showInfo(item)},if(restoreFocusPending&&item.id==lastFocusedId)returnFocusRequester else null,groupEdge){open(item)}}}}
    }
  }}}};if(infoLoading)AlertDialog(onDismissRequest={},title={Text("Caricamento informazioni…")},text={Box(Modifier.fillMaxWidth(),contentAlignment=Alignment.Center){CircularProgressIndicator()}},confirmButton={});mediaDetails?.let{MediaInfoDialog(it){mediaDetails=null}};if(exitDialog)AlertDialog(onDismissRequest={exitDialog=false},title={Text("Vuoi uscire da LM IPTV?")},text={Text("La playlist e i preferiti rimarranno salvati.")},confirmButton={TextButton(onClick={val activity=context as ComponentActivity;activity.finishAndRemoveTask()}){Text("ESCI")}},dismissButton={Button(onClick={exitDialog=false}){Text("ANNULLA")}})}
@Composable fun DigitalClock(){var tick by remember{mutableLongStateOf(System.currentTimeMillis())};LaunchedEffect(Unit){while(true){tick=System.currentTimeMillis();delay(1_000)}};val zone=java.util.TimeZone.getTimeZone("Europe/Rome");val time=remember(tick){java.text.SimpleDateFormat("HH:mm",java.util.Locale.ITALY).apply{timeZone=zone}.format(java.util.Date(tick))};val date=remember(tick){java.text.SimpleDateFormat("dd MMM",java.util.Locale.ITALY).apply{timeZone=zone}.format(java.util.Date(tick))};Column(horizontalAlignment=Alignment.End){Text(time,fontSize=18.sp,fontWeight=FontWeight.Bold,color=Color.White,letterSpacing=1.sp);Text(date.uppercase(),fontSize=8.sp,fontWeight=FontWeight.SemiBold,color=Color(0xFF9EABC0),letterSpacing=.8.sp)}}
@Composable fun SplashScreen(){val alpha=remember{Animatable(0f)};val scale=remember{Animatable(.72f)};LaunchedEffect(Unit){alpha.animateTo(1f,tween(620));scale.animateTo(1.05f,tween(720));scale.animateTo(1f,tween(260));delay(1250);alpha.animateTo(0f,tween(520))};Box(Modifier.fillMaxSize().background(Color.Black),contentAlignment=Alignment.Center){Column(Modifier.graphicsLayer{this.alpha=alpha.value;scaleX=scale.value;scaleY=scale.value},horizontalAlignment=Alignment.CenterHorizontally){Image(painterResource(R.drawable.lm_logo),"Logo LM IPTV",Modifier.size(150.dp));Spacer(Modifier.height(8.dp));Text("LM IPTV",fontSize=20.sp,fontWeight=FontWeight.Bold,color=Color.White,letterSpacing=2.sp)}}}
@Composable fun PreloadScreen(profile:String,label:String,done:Int,total:Int){var discovery by remember{mutableFloatStateOf(0.04f)};LaunchedEffect(total){if(total<=0)while(discovery<0.92f){delay(180);discovery=(discovery+0.012f+(1f-discovery)*0.018f).coerceAtMost(0.92f)}};val target=if(total<=0)discovery else(done.toFloat()/total.coerceAtLeast(1)).coerceIn(0f,1f);val progress by animateFloatAsState(target,tween(650),label="preload-progress");val pulse=rememberInfiniteTransition(label="loading-pulse");val scale by pulse.animateFloat(.96f,1.04f,infiniteRepeatable(tween(850),RepeatMode.Reverse),label="logo-pulse");MaterialTheme(colorScheme=darkColorScheme(primary=Color(0xFF3EE7E1),onSurface=Color.White)){Box(Modifier.fillMaxSize().background(Brush.radialGradient(listOf(Color(0xFF173D7B),Color(0xFF071326),Color(0xFF03050B)),radius=1250f)),contentAlignment=Alignment.Center){Column(Modifier.width(570.dp),horizontalAlignment=Alignment.CenterHorizontally){Image(painterResource(R.drawable.lm_logo),"LM IPTV",Modifier.size(96.dp).graphicsLayer{scaleX=scale;scaleY=scale});Spacer(Modifier.height(22.dp));Text("Preparazione di $profile",fontSize=25.sp,fontWeight=FontWeight.Bold,color=Color.White);Spacer(Modifier.height(10.dp));Text(label,fontSize=14.sp,color=Color(0xFFE0E8F5),maxLines=1,overflow=TextOverflow.Ellipsis);Spacer(Modifier.height(26.dp));LinearProgressIndicator(progress={progress},modifier=Modifier.fillMaxWidth().height(10.dp).clip(RoundedCornerShape(50)),color=Color(0xFF3EE7E1),trackColor=Color(0xFF243754));Spacer(Modifier.height(12.dp));Text("${(progress*100).toInt()}%",fontSize=17.sp,fontWeight=FontWeight.Bold,color=Color.White);if(total>0)Text("Fase ${done.coerceAtMost(total)} di $total",fontSize=11.sp,color=Color(0xFF9CAAC0));Spacer(Modifier.height(8.dp));Text("Stiamo preparando i contenuti per rendere LM IPTV più fluida e veloce.",fontSize=11.sp,color=Color(0xFF91A2BA))}}}}
@Composable fun CategorySetupScreen(categories:Map<String,List<Category>>,hidden:Set<String>,onToggle:(String)->Unit,onContinue:()->Unit){
  val kinds=listOf("LIVE","FILM","SERIE");var selectedKind by remember{mutableStateOf(kinds.firstOrNull{categories[it].orEmpty().isNotEmpty()}?:"LIVE")};var expanded by remember{mutableStateOf(false)}
  val selected=categories.flatMap{(kind,cats)->cats.map{"$kind:${it.id}"}}.count{!hidden.contains(it)};val current=categories[selectedKind].orEmpty();val label=when(selectedKind){"LIVE"->"TV IN DIRETTA";"FILM"->"FILM";else->"SERIE TV"}
  MaterialTheme(colorScheme=darkColorScheme(primary=Color(0xFF3EE7E1),onSurface=Color.White)){Column(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0xFF102957),Color(0xFF050812)))).padding(36.dp)){
    Text("Scegli cosa caricare",fontSize=27.sp,fontWeight=FontWeight.Bold,color=Color.White);Text("Apri il menu, scegli Live, Film o Serie e seleziona soltanto i gruppi che vuoi vedere.",fontSize=13.sp,color=Color(0xFFD4DCE9));Spacer(Modifier.height(18.dp))
    Box{FocusActionButton("CATEGORIA: $label  ▼",onClick={expanded=true},modifier=Modifier.width(310.dp));DropdownMenu(expanded=expanded,onDismissRequest={expanded=false}){kinds.filter{categories[it].orEmpty().isNotEmpty()}.forEach{kind->DropdownMenuItem(text={Text(when(kind){"LIVE"->"TV IN DIRETTA";"FILM"->"FILM";else->"SERIE TV"},fontSize=15.sp,fontWeight=FontWeight.Bold)},onClick={selectedKind=kind;expanded=false})}}}
    Spacer(Modifier.height(14.dp));Row{FocusActionButton("SELEZIONA TUTTO",onClick={current.forEach{val key="$selectedKind:${it.id}";if(hidden.contains(key))onToggle(key)}},modifier=Modifier.width(205.dp));Spacer(Modifier.width(12.dp));FocusActionButton("DESELEZIONA TUTTO",onClick={current.forEach{val key="$selectedKind:${it.id}";if(!hidden.contains(key))onToggle(key)}},modifier=Modifier.width(225.dp),danger=true)}
    Spacer(Modifier.height(14.dp));Box(Modifier.weight(1f)){GroupVisibilitySettings(mapOf(selectedKind to current),hidden,onToggle,{_,_->},emptyList(),false)};Spacer(Modifier.height(12.dp));FocusActionButton(if(selected>0)"SALVA E CARICA $selected GRUPPI"else"SCEGLI ALMENO UN GRUPPO",onClick=onContinue,enabled=selected>0,modifier=Modifier.align(Alignment.End).width(300.dp).height(54.dp))
  }}
}
@Composable fun ProfileSelector(profiles:List<PlaylistProfile>,onSelect:(PlaylistProfile)->Unit,onAvatar:(PlaylistProfile)->Unit,onAdd:()->Unit){val avatars=listOf(R.drawable.avatar_pro_1,R.drawable.avatar_pro_2,R.drawable.avatar_pro_3,R.drawable.avatar_pro_4,R.drawable.avatar_anime_1,R.drawable.avatar_anime_2,R.drawable.avatar_anime_3,R.drawable.avatar_anime_4,R.drawable.avatar_fun_1,R.drawable.avatar_fun_2,R.drawable.avatar_fun_3,R.drawable.avatar_fun_4);MaterialTheme(colorScheme=darkColorScheme(background=Color(0xFF050812),primary=Color(0xFF3EE7E1),onSurface=Color.White)){Column(Modifier.fillMaxSize().background(Brush.radialGradient(listOf(Color(0xFF19366D),Color(0xFF050812)),radius=1100f)).padding(48.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("Chi sta guardando?",fontSize=30.sp,fontWeight=FontWeight.Bold,color=Color.White);Text("Scegli la playlist",color=Color(0xFFB8C2D3));Spacer(Modifier.height(28.dp));LazyRow(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.Center){items(profiles){profile->var focus by remember{mutableStateOf(false)};Column(Modifier.width(205.dp).onFocusChanged{focus=it.isFocused}.graphicsLayer{scaleX=if(focus)1.04f else 1f;scaleY=if(focus)1.04f else 1f}.clickable(indication=null,interactionSource=remember{MutableInteractionSource()}){onSelect(profile)}.focusable(),horizontalAlignment=Alignment.CenterHorizontally){Image(painterResource(avatars[profile.avatar%avatars.size]),profile.name,Modifier.size(132.dp).clip(CircleShape).border(if(focus)4.dp else 1.dp,if(focus)Color.White else Color(0x44FFFFFF),CircleShape),contentScale=ContentScale.Crop);Spacer(Modifier.height(10.dp));Text(profile.name,fontSize=15.sp,fontWeight=FontWeight.SemiBold,color=Color.White,maxLines=1);TextButton(onClick={onAvatar(profile)}){Text("CAMBIA AVATAR",fontSize=9.sp,color=Color(0xFF3EE7E1))}}};item{var focus by remember{mutableStateOf(false)};Box(Modifier.padding(top=36.dp,start=16.dp).size(76.dp).graphicsLayer{scaleX=if(focus)1.08f else 1f;scaleY=if(focus)1.08f else 1f}.onFocusChanged{focus=it.isFocused}.background(if(focus)Color.White else Color(0xFF192B49),CircleShape).clickable(indication=null,interactionSource=remember{MutableInteractionSource()},onClick=onAdd).focusable(),contentAlignment=Alignment.Center){Text("+",fontSize=34.sp,fontWeight=FontWeight.Light,color=if(focus)Color.Black else Color.White)}}}}}}

@Composable fun HomeDashboard(movies:List<IptvItem>,live:List<IptvItem>,favorites:List<IptvItem>,continueWatching:List<IptvItem>,epg:Map<String,String>,onOpen:(IptvItem)->Unit,onClearContinue:()->Unit){
  val featuredItems=movies.take(12).ifEmpty{live.take(12)};var featuredIndex by remember(featuredItems){mutableIntStateOf(0)};LaunchedEffect(featuredItems){while(featuredItems.size>1){delay(3000);featuredIndex=(featuredIndex+1)%featuredItems.size}};val featured=featuredItems.getOrNull(featuredIndex);LazyColumn(Modifier.fillMaxSize(),verticalArrangement=Arrangement.spacedBy(16.dp),contentPadding=PaddingValues(bottom=36.dp)){
    if(featured!=null)item{Crossfade(targetState=featured,animationSpec=tween(850),label="film-in-evidenza"){shown->Box(Modifier.fillMaxWidth().height(265.dp).background(Color(0xFF09111E),RoundedCornerShape(12.dp))){if(shown.image.isNotBlank())AsyncImage(shown.image,shown.title,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Brush.horizontalGradient(listOf(Color(0xFF050812),Color(0xE8050812),Color(0x22050812)))));Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color.Transparent,Color(0xAA050812)))));Column(Modifier.align(Alignment.CenterStart).width(440.dp).padding(34.dp)){Text(if(shown.kind=="LIVE")"ORA IN TV"else"IN EVIDENZA",fontSize=9.sp,fontWeight=FontWeight.Bold,color=Color(0xFF3EE7E1),letterSpacing=1.5.sp);Spacer(Modifier.height(8.dp));Text(shown.title,fontSize=27.sp,fontWeight=FontWeight.Bold,maxLines=2,overflow=TextOverflow.Ellipsis);Spacer(Modifier.height(7.dp));Text(epgTitle(epg[shown.id])?:shown.group,fontSize=12.sp,color=Color(0xFFD0D6E1),maxLines=2);Spacer(Modifier.height(16.dp));Button(onClick={onOpen(shown)},contentPadding=PaddingValues(horizontal=20.dp,vertical=9.dp)){Text("▶  GUARDA",fontSize=11.sp,fontWeight=FontWeight.Bold)}}}}}
    if(movies.isNotEmpty())item{HomeRail("Film scelti per te",movies.take(24),epg,onOpen)}
    if(live.isNotEmpty())item{HomeRail("Canali in evidenza",live.take(24),epg,onOpen)}
    if(continueWatching.isNotEmpty())item{HomeRail("Continua a guardare",continueWatching.take(24),epg,onOpen,onClearContinue)}
    if(favorites.isNotEmpty())item{HomeRail("I miei preferiti",favorites.take(18),epg,onOpen)}
    if(movies.isEmpty()&&live.isEmpty())item{Box(Modifier.fillMaxWidth().height(280.dp),contentAlignment=Alignment.Center){Text("Aggiungi o seleziona una playlist per iniziare",fontSize=15.sp,color=Color(0xFFB8C2D3))}}
  }
}
@Composable fun HomeRail(title:String,items:List<IptvItem>,epg:Map<String,String>,onOpen:(IptvItem)->Unit,onClear:(()->Unit)?=null){Column{Row(verticalAlignment=Alignment.CenterVertically){Text(title,fontSize=15.sp,fontWeight=FontWeight.SemiBold);Spacer(Modifier.weight(1f));if(onClear!=null)TextButton(onClick=onClear){Text("ELIMINA TUTTO",fontSize=9.sp,color=Color(0xFFFF8997))}};Spacer(Modifier.height(8.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(12.dp),contentPadding=PaddingValues(horizontal=3.dp,vertical=4.dp)){items(items,key={it.id}){item->HomeTile(item,epg[item.id]){onOpen(item)}}}}}
@Composable fun HomeTile(item:IptvItem,now:String?,onClick:()->Unit){var focus by remember{mutableStateOf(false)};Column(Modifier.width(218.dp).graphicsLayer{scaleX=if(focus)1.045f else 1f;scaleY=if(focus)1.045f else 1f}.onFocusChanged{focus=it.isFocused}.border(if(focus)3.dp else 1.dp,if(focus)Color.White else Color(0x22FFFFFF),RoundedCornerShape(8.dp)).background(Color(0xFF101827),RoundedCornerShape(8.dp)).clickable(onClick=onClick).focusable()){Box(Modifier.fillMaxWidth().height(115.dp),contentAlignment=Alignment.Center){if(item.image.isNotBlank())AsyncImage(item.image,item.title,Modifier.fillMaxSize().padding(if(item.kind=="LIVE")10.dp else 0.dp),contentScale=if(item.kind=="LIVE")ContentScale.Fit else ContentScale.Crop)else Text("LM",fontSize=22.sp,fontWeight=FontWeight.Black,color=Color(0xFF3EE7E1))};Column(Modifier.padding(horizontal=9.dp,vertical=7.dp)){Text(item.title,fontSize=10.sp,fontWeight=FontWeight.SemiBold,maxLines=2);Text(epgTitle(now)?:item.group,fontSize=9.sp,color=Color(0xFF93A1B8),maxLines=1,overflow=TextOverflow.Ellipsis)}}}

@Composable fun SearchScreen(items:List<IptvItem>,query:String,loading:Boolean,epg:Map<String,String>,onOpen:(IptvItem)->Unit,onInfo:(IptvItem)->Unit){val results=if(query.length<2)emptyList()else items.filter{it.title.contains(query,true)};if(loading)Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){CircularProgressIndicator();Spacer(Modifier.height(12.dp));Text("Indicizzazione rapida dei titoli…",color=Color.White)}}else if(query.length<2)Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("Scrivi almeno due lettere per cercare nei titoli",color=Color(0xFFB8C2D3),fontSize=14.sp)}else if(results.isEmpty())Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("Nessun risultato",color=Color.White)}else LazyVerticalGrid(GridCells.Fixed(4),horizontalArrangement=Arrangement.spacedBy(14.dp),verticalArrangement=Arrangement.spacedBy(15.dp),contentPadding=PaddingValues(4.dp,4.dp,4.dp,30.dp)){items(results,key={it.id}){item->MediaCard(item,epg[item.id],false,{},{onInfo(item)}){onOpen(item)}}}}
@Composable fun GuideTvScreen(items:List<IptvItem>,epg:Map<String,String>,onOpen:(IptvItem)->Unit){LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp),contentPadding=PaddingValues(bottom=30.dp)){items(items,key={it.id}){item->var focus by remember{mutableStateOf(false)};Row(Modifier.fillMaxWidth().height(70.dp).onFocusChanged{focus=it.isFocused}.border(if(focus)2.dp else 1.dp,if(focus)Color.White else Color(0x22FFFFFF),RoundedCornerShape(9.dp)).background(if(focus)Color(0xFF1B3152)else Color(0xD90D1727),RoundedCornerShape(9.dp)).clickable{onOpen(item)}.focusable().padding(horizontal=14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.width(95.dp).fillMaxHeight(),contentAlignment=Alignment.Center){if(item.image.isNotBlank())AsyncImage(item.image,item.title,Modifier.fillMaxSize().padding(9.dp),contentScale=ContentScale.Fit)else Text("LM",color=Color(0xFF3EE7E1))};Spacer(Modifier.width(14.dp));Column(Modifier.width(260.dp)){Text(item.title,color=Color.White,fontSize=12.sp,fontWeight=FontWeight.SemiBold,maxLines=2);Text(item.group,color=Color(0xFF93A1B8),fontSize=10.sp)};Box(Modifier.width(3.dp).height(38.dp).background(Color(0xFF3EE7E1),RoundedCornerShape(2.dp)));Spacer(Modifier.width(14.dp));Column{Text("IN ONDA",fontSize=9.sp,color=Color(0xFF3EE7E1),fontWeight=FontWeight.Bold);Text(epgTitle(epg[item.id])?:"Programmazione non fornita dal server",color=Color.White,fontSize=12.sp,maxLines=1,overflow=TextOverflow.Ellipsis);Text(epgTime(epg[item.id])?:"Orario non disponibile",color=Color(0xFF9AA9BF),fontSize=10.sp)}}}}}

@Composable fun Settings(name:String,onName:(String)->Unit,url:String,onUrl:(String)->Unit,loading:Boolean,error:String,onImport:()->Unit,categories:Map<String,List<Category>>,hidden:Set<String>,onToggle:(String)->Unit,onMove:(String,Int)->Unit,order:List<String>,profiles:List<PlaylistProfile>,onSaveProfile:(PlaylistProfile,PlaylistProfile)->Unit,onDeleteProfile:(PlaylistProfile)->Unit,onPhoneSaved:(String,String)->Unit){var page by remember{mutableStateOf("PLAYLIST")};var expires by remember(url){mutableStateOf("Verifica in corso…")};val mac=remember{deviceMacAddress()};LaunchedEffect(url){expires=parseXtream(url)?.let{withContext(Dispatchers.IO){subscriptionExpiry(it)}}?:"Non disponibile per playlist M3U"};Column{LazyRow(horizontalArrangement=Arrangement.spacedBy(10.dp)){item{TvChip(if(loading)"Aggiornamento…"else"Aggiorna playlist",false){onImport()}};item{TvChip("Playlist e QR",page=="PLAYLIST"){page="PLAYLIST"}};item{TvChip("Gestisci playlist",page=="GESTIONE"){page="GESTIONE"}};item{TvChip("Gestisci gruppi",page=="GRUPPI"){page="GRUPPI"}}};Spacer(Modifier.height(10.dp));Text("INDIRIZZO MAC DISPOSITIVO  •  $mac",fontSize=10.sp,fontWeight=FontWeight.SemiBold,color=Color(0xFF9FB0C7),modifier=Modifier.background(Color(0x99111A2A),RoundedCornerShape(10.dp)).padding(horizontal=14.dp,vertical=9.dp));Spacer(Modifier.height(12.dp));when(page){"GRUPPI"->GroupVisibilitySettings(categories,hidden,onToggle,onMove,order);"GESTIONE"->PlaylistManagement(profiles,onSaveProfile,onDeleteProfile);else->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(25.dp)){Column(Modifier.weight(1f).background(Color(0xBB0D1422),RoundedCornerShape(16.dp)).padding(24.dp),verticalArrangement=Arrangement.spacedBy(13.dp)){Text("Playlist",fontSize=19.sp,fontWeight=FontWeight.SemiBold);Text("Scadenza: $expires",fontSize=11.sp,color=Color(0xFF3EE7E1));OutlinedTextField(name,onName,label={Text("Nome playlist")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(url,onUrl,label={Text("Link M3U / M3U8")},singleLine=true,modifier=Modifier.fillMaxWidth());Button(onClick=onImport,enabled=!loading,modifier=Modifier.height(50.dp)){Text(if(loading)"AGGIORNAMENTO…"else"AGGIORNA PLAYLIST")};if(error.isNotBlank())Text(error,color=Color(0xFFFF8295))};PairingPanel(Modifier.width(370.dp),onPhoneSaved)}}}}

@Composable fun PlaylistManagement(profiles:List<PlaylistProfile>,onSave:(PlaylistProfile,PlaylistProfile)->Unit,onDelete:(PlaylistProfile)->Unit){var editing by remember{mutableStateOf<PlaylistProfile?>(null)};var deleting by remember{mutableStateOf<PlaylistProfile?>(null)};var editName by remember{mutableStateOf("")};var editUrl by remember{mutableStateOf("")};Column{Text("Le tue playlist",fontSize=20.sp,fontWeight=FontWeight.Bold);Text("Seleziona Modifica per cambiare nome o collegamento.",fontSize=11.sp,color=Color(0xFF9DAAC0));Spacer(Modifier.height(14.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(9.dp)){items(profiles,key={it.url}){profile->var rowFocused by remember{mutableStateOf(false)};Row(Modifier.fillMaxWidth().onFocusChanged{rowFocused=it.hasFocus}.graphicsLayer{scaleX=if(rowFocused)1.025f else 1f;scaleY=if(rowFocused)1.025f else 1f}.border(if(rowFocused)2.dp else 1.dp,if(rowFocused)Color.White else Color.Transparent,RoundedCornerShape(10.dp)).background(Color(0xD0111A2A),RoundedCornerShape(10.dp)).padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(profile.name,fontSize=14.sp,fontWeight=FontWeight.SemiBold,color=Color.White);Text(profile.url.substringBefore('?'),fontSize=9.sp,color=Color(0xFF8FA0B7),maxLines=1,overflow=TextOverflow.Ellipsis)};ManageButton("MODIFICA",false){editing=profile;editName=profile.name;editUrl=profile.url};Spacer(Modifier.width(9.dp));ManageButton("ELIMINA",true){deleting=profile}}}}};if(editing!=null)AlertDialog(onDismissRequest={editing=null},title={Text("Modifica playlist")},text={Column(verticalArrangement=Arrangement.spacedBy(10.dp)){OutlinedTextField(editName,{editName=it},label={Text("Nome")},singleLine=true);OutlinedTextField(editUrl,{editUrl=it},label={Text("Link M3U / Xtream")},singleLine=true)}},confirmButton={Button(onClick={val old=editing!!;onSave(old,old.copy(name=editName.trim().ifBlank{old.name},url=editUrl.trim().ifBlank{old.url}));editing=null}){Text("SALVA")}},dismissButton={TextButton(onClick={editing=null}){Text("ANNULLA")}});if(deleting!=null)AlertDialog(onDismissRequest={deleting=null},title={Text("Eliminare ${deleting!!.name}?")},text={Text("La playlist e il catalogo salvato verranno rimossi da questa Fire TV.")},confirmButton={Button(onClick={onDelete(deleting!!);deleting=null},colors=ButtonDefaults.buttonColors(containerColor=Color(0xFF9E2635))){Text("ELIMINA")}},dismissButton={TextButton(onClick={deleting=null}){Text("ANNULLA")}})}
@Composable fun ManageButton(text:String,danger:Boolean,onClick:()->Unit){var focused by remember{mutableStateOf(false)};Button(onClick=onClick,modifier=Modifier.height(44.dp).onFocusChanged{focused=it.isFocused}.graphicsLayer{scaleX=if(focused)1.16f else 1f;scaleY=if(focused)1.16f else 1f}.border(if(focused)3.dp else 0.dp,Color.White,RoundedCornerShape(22.dp)),colors=ButtonDefaults.buttonColors(containerColor=if(focused)Color.White else if(danger)Color(0xFF8F2432)else Color(0xFF27436D),contentColor=if(focused)Color.Black else Color.White),contentPadding=PaddingValues(horizontal=18.dp)){Text(if(focused)"●  $text"else text,fontSize=10.sp,fontWeight=FontWeight.Bold)}}
@Composable fun FocusActionButton(text:String,onClick:()->Unit,modifier:Modifier=Modifier,danger:Boolean=false,enabled:Boolean=true){var focused by remember{mutableStateOf(false)};Button(onClick=onClick,enabled=enabled,modifier=modifier.heightIn(min=48.dp).onFocusChanged{focused=it.isFocused}.graphicsLayer{scaleX=if(focused)1.07f else 1f;scaleY=if(focused)1.07f else 1f}.border(if(focused)3.dp else 0.dp,Color.White,RoundedCornerShape(12.dp)),colors=ButtonDefaults.buttonColors(containerColor=if(focused)Color.White else if(danger)Color(0xFF8F2432)else Color(0xFF203A63),contentColor=if(focused)Color.Black else Color.White,disabledContainerColor=Color(0xFF263044),disabledContentColor=Color(0xFF8D98AA)),contentPadding=PaddingValues(horizontal=18.dp,vertical=12.dp)){Text(text,fontSize=12.sp,fontWeight=FontWeight.ExtraBold,maxLines=2)}}
@Composable fun MediaInfoDialog(info:MediaDetails,onClose:()->Unit){
  AlertDialog(
    onDismissRequest=onClose,
    containerColor=Color(0xFF0D1728),
    titleContentColor=Color.White,
    title={Column{Text("INFORMAZIONI",fontSize=11.sp,fontWeight=FontWeight.Bold,color=Color(0xFF3EE7E1),letterSpacing=1.4.sp);Spacer(Modifier.height(5.dp));Text(info.title,fontSize=23.sp,lineHeight=27.sp,fontWeight=FontWeight.ExtraBold,maxLines=3)}},
    text={LazyColumn(Modifier.width(620.dp).heightIn(max=450.dp).background(Color(0xFF121F34),RoundedCornerShape(12.dp)).padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){
      if(info.plot.isNotBlank())item{Column{Text("TRAMA",fontSize=11.sp,fontWeight=FontWeight.Bold,color=Color(0xFF3EE7E1));Spacer(Modifier.height(5.dp));Text(info.plot,fontSize=15.sp,lineHeight=21.sp,color=Color.White)}}
      listOf("Anno" to info.year,"Genere" to info.genre,"Valutazione" to info.rating,"Durata" to info.duration,"Regia" to info.director,"Cast" to info.cast).filter{it.second.isNotBlank()}.forEach{(label,value)->item{Column{Text(label.uppercase(),fontSize=10.sp,fontWeight=FontWeight.Bold,color=Color(0xFF91A3BC));Text(value,fontSize=14.sp,lineHeight=19.sp,fontWeight=FontWeight.SemiBold,color=Color.White)}}}
    }},
    confirmButton={FocusActionButton("CHIUDI",onClick=onClose,modifier=Modifier.width(160.dp))}
  )
}
@Composable fun GroupVisibilitySettings(categories:Map<String,List<Category>>,hidden:Set<String>,onToggle:(String)->Unit,onMove:(String,Int)->Unit,order:List<String>,showReorder:Boolean=true){LazyColumn(verticalArrangement=Arrangement.spacedBy(7.dp),contentPadding=PaddingValues(bottom=30.dp)){listOf("LIVE","FILM","SERIE").forEach{kind->item{Row(verticalAlignment=Alignment.CenterVertically){Text(when(kind){"LIVE"->"TV IN DIRETTA";"FILM"->"FILM";else->"SERIE TV"},fontSize=12.sp,fontWeight=FontWeight.Bold,color=Color(0xFF3EE7E1),modifier=Modifier.padding(top=10.dp,bottom=3.dp));Spacer(Modifier.weight(1f));TextButton(onClick={categories[kind].orEmpty().forEach{val k="$kind:${it.id}";if(hidden.contains(k))onToggle(k)}}){Text("SELEZIONA TUTTO",fontSize=9.sp)};TextButton(onClick={categories[kind].orEmpty().forEach{val k="$kind:${it.id}";if(!hidden.contains(k))onToggle(k)}}){Text("DESELEZIONA TUTTO",fontSize=9.sp)}}};items(categories[kind].orEmpty().sortedBy{val p=order.indexOf("$kind:${it.id}");if(p<0)Int.MAX_VALUE else p},key={"$kind:${it.id}"}){cat->val key="$kind:${cat.id}";var rowFocused by remember{mutableStateOf(false)};Row(Modifier.fillMaxWidth().height(52.dp).onFocusChanged{rowFocused=it.hasFocus}.graphicsLayer{scaleX=if(rowFocused)1.025f else 1f;scaleY=if(rowFocused)1.025f else 1f}.border(if(rowFocused)2.dp else 1.dp,if(rowFocused)Color.White else Color.Transparent,RoundedCornerShape(8.dp)).background(Color(0xC00D1727),RoundedCornerShape(8.dp)).padding(horizontal=14.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(checked=!hidden.contains(key),onCheckedChange={onToggle(key)});Spacer(Modifier.width(10.dp));Text(cat.name,color=Color.White,fontSize=12.sp);Spacer(Modifier.weight(1f));Text(if(hidden.contains(key))"NASCOSTO"else"VISIBILE",fontSize=9.sp,color=if(hidden.contains(key))Color(0xFFFF8295)else Color(0xFF6EE7B7));if(showReorder){Spacer(Modifier.width(12.dp));ReorderButton("↑"){onMove(key,-1)};Spacer(Modifier.width(7.dp));ReorderButton("↓"){onMove(key,1)}}}}}}}
@Composable fun ReorderButton(symbol:String,onClick:()->Unit){var focused by remember{mutableStateOf(false)};Button(onClick=onClick,modifier=Modifier.size(42.dp).onFocusChanged{focused=it.isFocused}.graphicsLayer{scaleX=if(focused)1.13f else 1f;scaleY=if(focused)1.13f else 1f},contentPadding=PaddingValues(0.dp),colors=ButtonDefaults.buttonColors(containerColor=if(focused)Color.White else Color(0xFF243650),contentColor=if(focused)Color.Black else Color.White)){Text(symbol,fontSize=18.sp,fontWeight=FontWeight.Bold)}}

@Composable fun PairingPanel(modifier:Modifier,onSaved:(String,String)->Unit){val activity=LocalContext.current as ComponentActivity;val ip=remember{localIpv4()};val pin=remember{(100000..999999).random().toString()};val address=if(ip==null)""else"http://$ip:8766/?pin=$pin";val server=remember(ip,pin){if(ip==null)null else PairingServer(8766,pin){name,url->activity.runOnUiThread{onSaved(name,url)}}};DisposableEffect(server){try{server?.start(3000,false)}catch(_:Exception){};onDispose{server?.stop()}};Column(modifier.background(Color(0xEE111A2A),RoundedCornerShape(20.dp)).padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("AGGIUNGI DAL TELEFONO",fontWeight=FontWeight.Black,color=Color(0xFF3EE7E1));Spacer(Modifier.height(8.dp));Text("Scansiona il QR con il telefono collegato allo stesso Wi-Fi.",fontSize=12.sp,color=Color(0xFF9BA7BC));Spacer(Modifier.height(16.dp));if(address.isNotBlank()){val qr=remember(address){qrBitmap(address,270)};Image(qr.asImageBitmap(),"QR per configurare la playlist",Modifier.size(270.dp));Spacer(Modifier.height(9.dp));Text("Codice $pin",fontWeight=FontWeight.Bold)}else Text("Connessione Wi-Fi non rilevata",color=Color(0xFFFF8295))}}

class PairingServer(port:Int,private val pin:String,private val saved:(String,String)->Unit):NanoHTTPD(port){override fun serve(session:IHTTPSession):Response{return try{if(session.parameters["pin"]?.firstOrNull()!=pin)return newFixedLengthResponse(Response.Status.FORBIDDEN,"text/plain","Codice non valido");if(session.method==Method.POST){session.parseBody(HashMap());val p=session.parameters;val name=p["name"]?.firstOrNull()?.trim().orEmpty().ifBlank{"Playlist telefono"};val mode=p["mode"]?.firstOrNull();val address=if(mode=="xtream"){val server=p["server"]?.firstOrNull()?.trim()?.trimEnd('/').orEmpty();val user=URLEncoder.encode(p["username"]?.firstOrNull().orEmpty(),"UTF-8");val pass=URLEncoder.encode(p["password"]?.firstOrNull().orEmpty(),"UTF-8");if(server.isBlank()||user.isBlank()||pass.isBlank())return newFixedLengthResponse(Response.Status.BAD_REQUEST,"text/html","Dati Xtream incompleti");"$server/get.php?username=$user&password=$pass&type=m3u_plus&output=ts"}else p["m3u"]?.firstOrNull()?.trim().orEmpty();if(address.isBlank())return newFixedLengthResponse(Response.Status.BAD_REQUEST,"text/html","Inserisci il collegamento");saved(name,address);return newFixedLengthResponse(Response.Status.OK,"text/html; charset=utf-8","<meta name='viewport' content='width=device-width'><body style='font-family:sans-serif;background:#07101b;color:white;padding:30px'><h1>Playlist salvata</h1><p>Puoi tornare su LM IPTV.</p></body>")};newFixedLengthResponse(Response.Status.OK,"text/html; charset=utf-8",pairingHtml(pin))}catch(e:Exception){newFixedLengthResponse(Response.Status.INTERNAL_ERROR,"text/plain","Errore: ${e.message}")}}}

fun pairingHtml(pin:String)="""<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:system-ui;background:#07101b;color:#fff;margin:0;padding:22px}main{max-width:580px;margin:auto}h1{color:#3ee7e1}section{background:#111b2c;padding:20px;border-radius:16px;margin:16px 0}input,select,button{box-sizing:border-box;width:100%;padding:14px;margin:7px 0;border-radius:10px;border:1px solid #34425b;background:#07101b;color:#fff}button{background:#3ee7e1;color:#06101a;font-weight:800;border:0}</style></head><body><main><h1>LM IPTV</h1><p>Configura la playlist sulla Fire TV.</p><form method="post" action="/?pin=$pin"><input name="name" placeholder="Nome playlist" required><select name="mode" onchange="document.getElementById('m3u').hidden=this.value!='m3u';document.getElementById('xt').hidden=this.value!='xtream'"><option value="m3u">Link M3U</option><option value="xtream">Xtream Codes</option></select><section id="m3u"><input name="m3u" placeholder="Link M3U / M3U8"></section><section id="xt" hidden><input name="server" placeholder="URL server"><input name="username" placeholder="Username"><input name="password" type="password" placeholder="Password"></section><button type="submit">SALVA SULLA FIRE TV</button></form></main></body></html>"""
fun localIpv4():String?{return try{Collections.list(NetworkInterface.getNetworkInterfaces()).flatMap{Collections.list(it.inetAddresses)}.firstOrNull{!it.isLoopbackAddress&&it.hostAddress?.contains(':')==false}?.hostAddress}catch(_:Exception){null}}
fun deviceMacAddress():String{return try{val interfaces=Collections.list(NetworkInterface.getNetworkInterfaces());val network=interfaces.firstOrNull{it.name.equals("wlan0",true)&&it.hardwareAddress!=null}?:interfaces.firstOrNull{!it.isLoopback&&it.hardwareAddress!=null};network?.hardwareAddress?.joinToString(":"){byte->"%02X".format(byte.toInt() and 0xFF)}?:"NON DISPONIBILE"}catch(_:Exception){"NON DISPONIBILE"}}
fun qrBitmap(text:String,size:Int):Bitmap{val matrix=QRCodeWriter().encode(text,BarcodeFormat.QR_CODE,size,size);return Bitmap.createBitmap(size,size,Bitmap.Config.RGB_565).also{bitmap->for(y in 0 until size)for(x in 0 until size)bitmap.setPixel(x,y,if(matrix[x,y])android.graphics.Color.BLACK else android.graphics.Color.WHITE)}}
@Composable fun TvNav(text:String,selected:Boolean,onClick:()->Unit){var focus by remember{mutableStateOf(false)};Text(text,color=if(selected||focus)Color.White else Color(0xFF8490A6),fontWeight=FontWeight.Bold,modifier=Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=4.dp).onFocusChanged{focus=it.isFocused}.background(if(selected||focus)Color(0xFF19345E)else Color.Transparent,RoundedCornerShape(10.dp)).clickable(onClick=onClick).focusable().padding(16.dp))}
@Composable fun SearchNav(selected:Boolean,onClick:()->Unit){var focus by remember{mutableStateOf(false)};Box(Modifier.size(42.dp).graphicsLayer{scaleX=if(focus)1.09f else 1f;scaleY=if(focus)1.09f else 1f}.onFocusChanged{focus=it.isFocused}.clickable(indication=null,interactionSource=remember{MutableInteractionSource()},onClick=onClick).focusable(),contentAlignment=Alignment.Center){Canvas(Modifier.size(19.dp)){val color=if(selected||focus)Color.White else Color(0xFF9AA6BA);drawCircle(color=color,radius=size.minDimension*.32f,center=center.copy(x=center.x-2f,y=center.y-2f),style=Stroke(width=2.2f));drawLine(color,start=center.copy(x=center.x+2f,y=center.y+2f),end=center.copy(x=size.width-1f,y=size.height-1f),strokeWidth=2.2f)}}}
@Composable fun TopNav(text:String,selected:Boolean,onClick:()->Unit){var focus by remember{mutableStateOf(false)};Text(text,color=if(selected||focus)Color.White else Color(0xFF9AA6BA),fontWeight=if(selected||focus)FontWeight.Bold else FontWeight.SemiBold,fontSize=11.sp,modifier=Modifier.graphicsLayer{scaleX=if(focus)1.09f else 1f;scaleY=if(focus)1.09f else 1f}.onFocusChanged{focus=it.isFocused}.clickable(indication=null,interactionSource=remember{MutableInteractionSource()},onClick=onClick).focusable().padding(horizontal=12.dp,vertical=9.dp))}
@Composable fun TvChip(text:String,selected:Boolean,onClick:()->Unit){var focus by remember{mutableStateOf(false)};Text(text,maxLines=1,fontSize=11.sp,fontWeight=if(focus)FontWeight.Bold else FontWeight.Medium,color=if(selected)Color(0xFF3EE7E1)else Color.White,modifier=Modifier.graphicsLayer{scaleX=if(focus)1.12f else 1f;scaleY=if(focus)1.12f else 1f}.onFocusChanged{focus=it.isFocused}.background(if(focus)Color(0xFF203554)else Color(0xFF141D2D),RoundedCornerShape(18.dp)).clickable(indication=null,interactionSource=remember{MutableInteractionSource()},onClick=onClick).focusable().padding(horizontal=15.dp,vertical=9.dp))}
@Composable fun MediaCard(item:IptvItem,now:String?,favorite:Boolean,onFavorite:()->Unit,onInfo:()->Unit,restoreRequester:FocusRequester?=null,onGroupStep:((Int)->Boolean)?=null,onClick:()->Unit){val vod=item.kind!="LIVE";var focus by remember{mutableStateOf(false)};var menu by remember{mutableStateOf(false)};var pressedAt by remember{mutableLongStateOf(0L)};var longPressed by remember{mutableStateOf(false)};Column(Modifier.then(if(restoreRequester!=null)Modifier.focusRequester(restoreRequester)else Modifier).height(288.dp).graphicsLayer{scaleX=if(focus)1.03f else 1f;scaleY=if(focus)1.03f else 1f}.onFocusChanged{focus=it.isFocused}.onPreviewKeyEvent{event->when{event.type==KeyEventType.KeyDown&&event.key==Key.DirectionLeft->onGroupStep?.invoke(-1)?:false;event.type==KeyEventType.KeyDown&&event.key==Key.DirectionRight->onGroupStep?.invoke(1)?:false;event.key!=Key.DirectionCenter->false;event.type==KeyEventType.KeyDown->{val nowMs=System.currentTimeMillis();if(pressedAt==0L)pressedAt=nowMs;if(nowMs-pressedAt>500){longPressed=true;true}else false};else->{pressedAt=0L;if(longPressed){longPressed=false;menu=true;true}else false}}}.border(if(focus)3.dp else 1.dp,if(focus)Color.White else Color(0x22FFFFFF),RoundedCornerShape(9.dp)).background(if(focus)Color(0xFF172B4A)else Color(0xEE0D1422),RoundedCornerShape(9.dp)).clickable(indication=null,interactionSource=remember{MutableInteractionSource()},onClick=onClick).focusable()){
  Box(Modifier.fillMaxWidth().height(168.dp).background(Color(0xFF090F1A),RoundedCornerShape(topStart=9.dp,topEnd=9.dp)),contentAlignment=Alignment.Center){if(item.image.isNotBlank())AsyncImage(model=item.image,contentDescription=item.title,contentScale=ContentScale.Fit,modifier=Modifier.fillMaxSize().padding(if(item.kind=="LIVE")11.dp else 3.dp))else Text("LM",fontSize=21.sp,fontWeight=FontWeight.Black,color=Color(0xFF3EE7E1))}
  Column(Modifier.padding(horizontal=12.dp,vertical=10.dp)){Text(item.title,fontSize=if(vod)16.sp else 15.sp,color=Color.White,fontWeight=FontWeight.ExtraBold,lineHeight=if(vod)19.sp else 18.sp,maxLines=if(vod)3 else 2);Spacer(Modifier.height(5.dp));Text(epgTitle(now)?:if(item.kind=="LIVE")"Programmazione non disponibile"else item.group,color=if(now!=null)Color.White else Color(0xFFD2D9E5),fontSize=12.sp,fontWeight=FontWeight.SemiBold,lineHeight=15.sp,maxLines=2,overflow=TextOverflow.Ellipsis);if(item.kind=="LIVE")Text(epgTime(now)?:"Orario non disponibile",color=Color(0xFFB6C2D4),fontSize=11.sp,fontWeight=FontWeight.Medium,maxLines=1,overflow=TextOverflow.Ellipsis)}
  if(menu)AlertDialog(onDismissRequest={menu=false},containerColor=Color(0xFF101A2B),titleContentColor=Color.White,title={Text(item.title,fontSize=20.sp,fontWeight=FontWeight.ExtraBold,maxLines=3)},text={Column(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("Scegli un’azione",fontSize=13.sp,color=Color(0xFFB9C5D8));FocusActionButton(if(favorite)"RIMUOVI DAI PREFERITI"else"AGGIUNGI AI PREFERITI",onClick={onFavorite();menu=false},modifier=Modifier.fillMaxWidth());if(item.kind!="LIVE")FocusActionButton("VEDI INFORMAZIONI",onClick={menu=false;onInfo()},modifier=Modifier.fillMaxWidth())}},confirmButton={},dismissButton={FocusActionButton("INDIETRO",onClick={menu=false},modifier=Modifier.width(150.dp),danger=true)})
}}
@Composable fun TvPlayer(item:IptvItem,now:String?,channelNumber:Int?,onClose:()->Unit,onPlayer:(ExoPlayer?,()->Unit)->Unit){
  val context=LocalContext.current;val prefs=remember{context.getSharedPreferences("lm_iptv_firetv",0)}
  var infoVisible by remember{mutableStateOf(true)};var controlsVisible by remember{mutableStateOf(true)};var infoPulse by remember{mutableIntStateOf(0)};var lastBackAt by remember{mutableLongStateOf(0L)}
  val reveal:()->Unit={infoVisible=true;controlsVisible=true;infoPulse++}
  LaunchedEffect(infoPulse){delay(3000);infoVisible=false;controlsVisible=false}
  val resumeKey="resume_${item.id}";val exo=remember(item.url){ExoPlayer.Builder(context).build().apply{setMediaItem(MediaItem.fromUri(item.url));prepare();if(item.kind!="LIVE")seekTo(prefs.getLong(resumeKey,0));playWhenReady=true}}
  var playbackPosition by remember{mutableLongStateOf(0L)}
  LaunchedEffect(exo){while(true){playbackPosition=exo.currentPosition;delay(250)}}
  DisposableEffect(exo){onPlayer(exo,reveal);onDispose{if(item.kind!="LIVE"){val position=exo.currentPosition;if(position>20_000&&exo.duration-position>60_000)prefs.edit().putLong(resumeKey,position).apply()else prefs.edit().remove(resumeKey).apply()};onPlayer(null,reveal);exo.release()}}
  BackHandler{val time=System.currentTimeMillis();if(time-lastBackAt<=2200)onClose()else{lastBackAt=time;Toast.makeText(context,"Premi ancora Indietro per uscire",Toast.LENGTH_SHORT).show()}}
  Box(Modifier.fillMaxSize().background(Color.Black)){
    AndroidView(factory={PlayerView(it).apply{keepScreenOn=true;player=exo;useController=true;controllerAutoShow=false;controllerHideOnTouch=true;controllerShowTimeoutMs=3000;setControllerVisibilityListener(PlayerView.ControllerVisibilityListener{visibility->controlsVisible=visibility==View.VISIBLE});setShowBuffering(PlayerView.SHOW_BUFFERING_WHEN_PLAYING);findViewById<DefaultTimeBar?>(androidx.media3.ui.R.id.exo_progress)?.apply{setPlayedColor(android.graphics.Color.rgb(229,9,20));setScrubberColor(android.graphics.Color.WHITE);setBufferedColor(android.graphics.Color.DKGRAY);setUnplayedColor(android.graphics.Color.GRAY)};layoutParams=FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT)}},modifier=Modifier.fillMaxSize())
    if(item.kind!="LIVE"&&controlsVisible)Text(formatPlaybackTime(playbackPosition),color=Color.White,fontSize=13.sp,fontWeight=FontWeight.Bold,modifier=Modifier.align(Alignment.BottomCenter).padding(bottom=42.dp).background(Color(0xBB000000),RoundedCornerShape(6.dp)).padding(horizontal=10.dp,vertical=4.dp))
    if(infoVisible){if(item.kind=="LIVE")Column(Modifier.fillMaxWidth().background(Brush.verticalGradient(listOf(Color(0xEE07101F),Color(0xC51A2740),Color(0x22000000)))).padding(horizontal=36.dp,vertical=20.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text(channelNumber?.toString()?:"TV",fontSize=40.sp,fontWeight=FontWeight.Light,color=Color.White,modifier=Modifier.width(76.dp));Column(Modifier.weight(1f)){Text(item.title,fontSize=21.sp,fontWeight=FontWeight.Bold,color=Color.White,maxLines=1,overflow=TextOverflow.Ellipsis);Text(epgTitle(now)?:"Programmazione non disponibile",fontSize=14.sp,fontWeight=FontWeight.SemiBold,color=Color.White,maxLines=1,overflow=TextOverflow.Ellipsis);Text(epgTime(now)?:"Orario non disponibile",fontSize=11.sp,color=Color(0xFFD7DEEA));epgDescription(now)?.let{Text(it,fontSize=10.sp,color=Color(0xFFBFC9D8),maxLines=2,overflow=TextOverflow.Ellipsis,modifier=Modifier.padding(top=3.dp))}}};epgProgress(now)?.let{value->Spacer(Modifier.height(10.dp));LinearProgressIndicator(progress={value},modifier=Modifier.fillMaxWidth().height(3.dp),color=Color.White,trackColor=Color(0x55FFFFFF))}}else Column(Modifier.fillMaxWidth().background(Brush.verticalGradient(listOf(Color(0xE6000000),Color.Transparent))).padding(horizontal=34.dp,vertical=26.dp)){Text(item.title,fontSize=23.sp,fontWeight=FontWeight.Bold,color=Color.White,maxLines=1,overflow=TextOverflow.Ellipsis)}}
  }
}

fun parseXtream(address:String):Xtream?{return try{val uri=Uri.parse(address);val user=uri.getQueryParameter("username")?:return null;val pass=uri.getQueryParameter("password")?:return null;Xtream("${uri.scheme}://${uri.encodedAuthority}",user,pass,address)}catch(_:Exception){null}}
fun subscriptionExpiry(x:Xtream):String{return try{val api="${x.server}/player_api.php?username=${Uri.encode(x.username)}&password=${Uri.encode(x.password)}";val info=JSONObject(httpText(api)).optJSONObject("user_info")?:return "Non disponibile";val raw=info.optString("exp_date");if(raw.isBlank()||raw=="null"||raw=="0")"Nessuna scadenza indicata"else java.text.SimpleDateFormat("dd/MM/yyyy",java.util.Locale.ITALY).format(java.util.Date(raw.toLong()*1000))}catch(_:Exception){"Non disponibile"}}
fun loadMediaDetails(x:Xtream,item:IptvItem):MediaDetails{val series=item.kind=="SERIE";val id=(if(series)item.seriesId else item.streamId).orEmpty();val action=if(series)"get_series_info&series_id"else"get_vod_info&vod_id";val api="${x.server}/player_api.php?username=${Uri.encode(x.username)}&password=${Uri.encode(x.password)}&action=$action=${Uri.encode(id)}";val root=JSONObject(httpText(api));val info=root.optJSONObject("info")?:root.optJSONObject("movie_data")?:root;fun value(vararg keys:String):String{for(key in keys){val found=info.optString(key);if(found.isNotBlank()&&found!="null")return found};return ""};return MediaDetails(item.title,value("plot","description","biography"),value("releaseDate","releasedate","year"),value("genre"),value("rating","rating_5based"),value("duration","duration_secs"),value("director"),value("cast","actors"))}
fun importSource(address:String):Imported{val x=parseXtream(address);if(x!=null){val base="${x.server}/player_api.php?username=${Uri.encode(x.username)}&password=${Uri.encode(x.password)}";val map=linkedMapOf<String,List<Category>>();map["LIVE"]=parseCategories(httpText("$base&action=get_live_categories"));map["FILM"]=parseCategories(httpText("$base&action=get_vod_categories"));map["SERIE"]=parseCategories(httpText("$base&action=get_series_categories"));if(map.values.all{it.isEmpty()})throw Exception("Il server non ha restituito categorie");return Imported(x,map,emptyList())};val all=parseM3u(address);return Imported(null,emptyMap(),all)}
fun parseCategories(text:String):List<Category>{val array=JSONArray(text);return List(array.length()){i->val row=array.getJSONObject(i);Category(row.optString("category_id"),row.optString("category_name","Altri"))}}
fun loadXtreamCategory(x:Xtream,section:String,category:Category):List<IptvItem>{val action=when(section){"LIVE"->"get_live_streams";"FILM"->"get_vod_streams";else->"get_series"};val base="${x.server}/player_api.php?username=${Uri.encode(x.username)}&password=${Uri.encode(x.password)}&action=$action&category_id=${Uri.encode(category.id)}";return parseXtreamItems(x,section,JSONArray(httpText(base)),mapOf(category.id to category.name))}
suspend fun loadFullCatalog(x:Xtream,categories:Map<String,List<Category>>):List<IptvItem> = coroutineScope{listOf("LIVE","FILM","SERIE").map{section->async(Dispatchers.IO){runCatching{val action=when(section){"LIVE"->"get_live_streams";"FILM"->"get_vod_streams";else->"get_series"};val base="${x.server}/player_api.php?username=${Uri.encode(x.username)}&password=${Uri.encode(x.password)}&action=$action";val names=categories[section].orEmpty().associate{it.id to it.name};parseXtreamItems(x,section,JSONArray(httpText(base)),names)}.getOrDefault(emptyList())}}.flatMap{it.await()}.distinctBy{it.id}}
fun parseXtreamItems(x:Xtream,section:String,array:JSONArray,categoryNames:Map<String,String>):List<IptvItem>{return List(array.length()){i->val row=array.getJSONObject(i);val id=if(section=="SERIE")row.optString("series_id")else row.optString("stream_id");val categoryId=row.optString("category_id");val group=categoryNames[categoryId]?:"Altri";val ext=row.optString("container_extension",if(section=="LIVE")"ts"else"mp4");val stream=when(section){"LIVE"->"${x.server}/live/${x.username}/${x.password}/$id.$ext";"FILM"->"${x.server}/movie/${x.username}/${x.password}/$id.$ext";else->""};val image=if(section=="SERIE")row.optString("cover")else row.optString("stream_icon");IptvItem("$section-$id",row.optString("name","Senza titolo"),stream,group,section,if(section=="SERIE")id else null,image,id,row.optString("epg_channel_id"))}}
fun loadEpisodes(x:Xtream,series:IptvItem):List<IptvItem>{val api="${x.server}/player_api.php?username=${Uri.encode(x.username)}&password=${Uri.encode(x.password)}&action=get_series_info&series_id=${Uri.encode(series.seriesId)}";val episodes=JSONObject(httpText(api)).optJSONObject("episodes")?:throw Exception("Nessun episodio disponibile");val result=mutableListOf<IptvItem>();for(season in episodes.keys()){val rows=episodes.optJSONArray(season)?:continue;for(i in 0 until rows.length()){val row=rows.getJSONObject(i);val id=row.optString("id");val ext=row.optString("container_extension","mp4");result+=IptvItem("EP-$id",row.optString("title","Episodio ${i+1}"),"${x.server}/series/${x.username}/${x.password}/$id.$ext","Stagione $season","EPISODIO",image=series.image)}};if(result.isEmpty())throw Exception("Nessun episodio disponibile");return result}

fun isAdult(value:String):Boolean{val text=value.lowercase();return listOf("xxx","adult","18+","erotic","porn").any{text.contains(it)}}
fun prepareHome(x:Xtream,categories:Map<String,List<Category>>):Pair<List<IptvItem>,List<IptvItem>>{val liveCats=categories["LIVE"].orEmpty();val preferred=listOf("italia","sky","dazn");val chosenLive=(preferred.mapNotNull{word->liveCats.firstOrNull{it.name.contains(word,true)}}+liveCats.take(1)).distinctBy{it.id}.take(4);val live=chosenLive.flatMap{runCatching{loadXtreamCategory(x,"LIVE",it).take(10)}.getOrDefault(emptyList())}.distinctBy{it.id};val movieCats=categories["FILM"].orEmpty().filterNot{isAdult(it.name)}.shuffled().take(4);val movies=movieCats.flatMap{runCatching{loadXtreamCategory(x,"FILM",it).shuffled().take(12)}.getOrDefault(emptyList())}.filterNot{isAdult(it.group)||isAdult(it.title)}.distinctBy{it.id}.shuffled();return live to movies}
fun loadCurrentPrograms(x:Xtream,channels:List<IptvItem>):Map<String,String>{val result=linkedMapOf<String,String>();for(channel in channels.take(80)){try{val base="${x.server}/player_api.php?username=${Uri.encode(x.username)}&password=${Uri.encode(x.password)}&stream_id=${Uri.encode(channel.streamId)}";var root=JSONObject(httpText("$base&action=get_short_epg&limit=8"));var rows=root.optJSONArray("epg_listings")?:root.optJSONArray("listings");if(rows==null||rows.length()==0){root=JSONObject(httpText("$base&action=get_simple_data_table"));rows=root.optJSONArray("epg_listings")?:root.optJSONArray("listings")};if(rows==null)continue;val now=System.currentTimeMillis()/1000;var fallback="";for(i in 0 until rows.length()){val row=rows.getJSONObject(i);val title=decodeEpg(row.optString("title"));val start=row.optLong("start_timestamp",row.optString("start_timestamp").toLongOrNull()?:0);val stop=row.optLong("stop_timestamp",row.optString("stop_timestamp").toLongOrNull()?:row.optLong("end_timestamp"));if(fallback.isBlank()&&title.isNotBlank())fallback=packEpg(title,start*1000,stop*1000);if(start>0&&stop>0&&start<=now&&stop>=now){result[channel.id]=packEpg(title,start*1000,stop*1000);break}};if(result[channel.id].isNullOrBlank()&&fallback.isNotBlank())result[channel.id]=fallback}catch(_:Exception){}};return result}
fun decodeEpg(value:String):String{if(value.isBlank())return "";return try{String(Base64.decode(value,Base64.DEFAULT),Charsets.UTF_8)}catch(_:Exception){value}}
fun readFavorites(text:String):List<IptvItem>{return try{val rows=JSONArray(text);List(rows.length()){i->val row=rows.getJSONObject(i);IptvItem(row.optString("id"),row.optString("title"),row.optString("url"),row.optString("group"),row.optString("kind"),row.optString("seriesId").ifBlank{null},row.optString("image"),row.optString("streamId"))}}catch(_:Exception){emptyList()}}
fun writeFavorites(items:List<IptvItem>):String{val rows=JSONArray();items.forEach{item->rows.put(JSONObject().put("id",item.id).put("title",item.title).put("url",item.url).put("group",item.group).put("kind",item.kind).put("seriesId",item.seriesId?:"").put("image",item.image).put("streamId",item.streamId))};return rows.toString()}
fun readProfiles(text:String):List<PlaylistProfile>{return try{val rows=JSONArray(text);List(rows.length()){i->val row=rows.getJSONObject(i);PlaylistProfile(row.optString("name","Playlist"),row.optString("url"),row.optInt("avatar",i%12))}.filter{it.url.isNotBlank()}}catch(_:Exception){emptyList()}}
fun writeProfiles(items:List<PlaylistProfile>):String{val rows=JSONArray();items.forEach{rows.put(JSONObject().put("name",it.name).put("url",it.url).put("avatar",it.avatar))};return rows.toString()}
fun readStringList(text:String):List<String>{return try{val rows=JSONArray(text);List(rows.length()){rows.optString(it)}}catch(_:Exception){emptyList()}}
fun writeStringList(items:List<String>):String{val rows=JSONArray();items.forEach{rows.put(it)};return rows.toString()}
fun httpText(address:String):String{val c=URL(address).openConnection() as HttpURLConnection;c.instanceFollowRedirects=true;c.connectTimeout=20_000;c.readTimeout=90_000;c.setRequestProperty("User-Agent","LMIPTV-FireTV/1.1");c.setRequestProperty("Accept-Encoding","gzip");if(c.responseCode !in 200..299)throw Exception("Errore server HTTP ${c.responseCode}");val input=if(c.contentEncoding?.contains("gzip",true)==true)GZIPInputStream(c.inputStream)else c.inputStream;return input.bufferedReader().use{it.readText()}}
fun parseM3u(address:String):List<IptvItem>{val c=URL(address).openConnection() as HttpURLConnection;c.instanceFollowRedirects=true;c.connectTimeout=20_000;c.readTimeout=120_000;c.setRequestProperty("User-Agent","LMIPTV-FireTV/1.1");if(c.responseCode !in 200..299)throw Exception("Errore server HTTP ${c.responseCode}");val input=if(c.contentEncoding?.contains("gzip",true)==true)GZIPInputStream(c.inputStream)else c.inputStream;val reader=BufferedReader(InputStreamReader(input));val result=mutableListOf<IptvItem>();var title="";var group="Altri";val regex=Regex("group-title=\\\"([^\\\"]*)\\\"",RegexOption.IGNORE_CASE);reader.useLines{lines->lines.forEach{raw->val line=raw.trim();if(line.startsWith("#EXTINF",true)){title=line.substringAfterLast(',').trim().ifBlank{"Senza nome"};group=regex.find(line)?.groupValues?.get(1)?.ifBlank{"Altri"}?:"Altri"}else if(line.isNotBlank()&&!line.startsWith("#")){val low=line.lowercase();val gl=group.lowercase();val kind=when{low.contains("/series/")||gl.contains("serie")->"SERIE";low.contains("/movie/")||gl.contains("film")||gl.contains("vod")||gl.contains("cinema")->"FILM";else->"LIVE"};result+=IptvItem("M3U-${result.size}",title.ifBlank{line.substringAfterLast('/')},line,group,kind)}}};if(result.isEmpty())throw Exception("Playlist vuota o non riconosciuta");return result}
























